// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	KeyExchange
	Message
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageID int32

const (
	MessageID_Done     MessageID = 0
	MessageID_Response MessageID = 1
	MessageID_ECDH     MessageID = 2
	MessageID_Nmap     MessageID = 3
	MessageID_Hash     MessageID = 4
	MessageID_Beacon   MessageID = 5
)

var MessageID_name = map[int32]string{
	0: "Done",
	1: "Response",
	2: "ECDH",
	3: "Nmap",
	4: "Hash",
	5: "Beacon",
}
var MessageID_value = map[string]int32{
	"Done":     0,
	"Response": 1,
	"ECDH":     2,
	"Nmap":     3,
	"Hash":     4,
	"Beacon":   5,
}

func (x MessageID) String() string {
	return proto.EnumName(MessageID_name, int32(x))
}
func (MessageID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type KeyExchange struct {
	ID          MessageID `protobuf:"varint,1,opt,name=ID,json=iD,enum=api.MessageID" json:"ID,omitempty"`
	IdentityKey []byte    `protobuf:"bytes,2,opt,name=IdentityKey,json=identityKey,proto3" json:"IdentityKey,omitempty"`
	Key         []byte    `protobuf:"bytes,3,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
}

func (m *KeyExchange) Reset()                    { *m = KeyExchange{} }
func (m *KeyExchange) String() string            { return proto.CompactTextString(m) }
func (*KeyExchange) ProtoMessage()               {}
func (*KeyExchange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KeyExchange) GetID() MessageID {
	if m != nil {
		return m.ID
	}
	return MessageID_Done
}

func (m *KeyExchange) GetIdentityKey() []byte {
	if m != nil {
		return m.IdentityKey
	}
	return nil
}

func (m *KeyExchange) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type Message struct {
	ID      MessageID `protobuf:"varint,1,opt,name=ID,json=iD,enum=api.MessageID" json:"ID,omitempty"`
	NextKey []byte    `protobuf:"bytes,2,opt,name=NextKey,json=nextKey,proto3" json:"NextKey,omitempty"`
	IO      []byte    `protobuf:"bytes,3,opt,name=IO,json=iO,proto3" json:"IO,omitempty"`
	Channel string    `protobuf:"bytes,4,opt,name=Channel,json=channel" json:"Channel,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetID() MessageID {
	if m != nil {
		return m.ID
	}
	return MessageID_Done
}

func (m *Message) GetNextKey() []byte {
	if m != nil {
		return m.NextKey
	}
	return nil
}

func (m *Message) GetIO() []byte {
	if m != nil {
		return m.IO
	}
	return nil
}

func (m *Message) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func init() {
	proto.RegisterType((*KeyExchange)(nil), "api.KeyExchange")
	proto.RegisterType((*Message)(nil), "api.Message")
	proto.RegisterEnum("api.MessageID", MessageID_name, MessageID_value)
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xbd, 0x6e, 0xc2, 0x30,
	0x14, 0x85, 0x6b, 0x3b, 0x25, 0xe4, 0x06, 0x45, 0x96, 0xa7, 0x4c, 0x55, 0xc4, 0x14, 0x75, 0x60,
	0x68, 0xdf, 0xa0, 0x18, 0x89, 0x08, 0x01, 0x52, 0xde, 0xe0, 0x36, 0xbd, 0x22, 0x56, 0x8b, 0x6d,
	0xd5, 0x19, 0xc8, 0xdb, 0x57, 0x06, 0xd4, 0x8c, 0x6c, 0xe7, 0x4f, 0xdf, 0x70, 0x20, 0x43, 0x6f,
	0x56, 0xfe, 0xd7, 0x0d, 0x4e, 0x09, 0xf4, 0x66, 0x89, 0x90, 0xef, 0x68, 0xdc, 0x5c, 0xba, 0x1e,
	0xed, 0x89, 0xd4, 0x0b, 0xf0, 0x46, 0x97, 0xac, 0x62, 0x75, 0xf1, 0x56, 0xac, 0xe2, 0x76, 0x4f,
	0x21, 0xe0, 0x89, 0x1a, 0xdd, 0x72, 0xa3, 0x55, 0x05, 0x79, 0xf3, 0x45, 0x76, 0x30, 0xc3, 0xb8,
	0xa3, 0xb1, 0xe4, 0x15, 0xab, 0x17, 0x6d, 0x6e, 0xa6, 0x48, 0x49, 0x10, 0xb1, 0x11, 0xd7, 0x46,
	0x7c, 0xd3, 0xb8, 0x3c, 0x43, 0x7a, 0x87, 0x3c, 0xc4, 0x97, 0x90, 0x1e, 0xe8, 0x32, 0x4c, 0xe8,
	0xd4, 0xde, 0xac, 0x2a, 0x80, 0x37, 0xc7, 0x3b, 0x95, 0x9b, 0x63, 0x5c, 0xae, 0x7b, 0xb4, 0x96,
	0x7e, 0xca, 0xa4, 0x62, 0x75, 0xd6, 0xa6, 0xdd, 0xcd, 0xbe, 0xee, 0x21, 0xfb, 0x87, 0xaa, 0x39,
	0x24, 0xda, 0x59, 0x92, 0x4f, 0x6a, 0x01, 0xf3, 0x96, 0x82, 0x77, 0x36, 0x90, 0x64, 0x31, 0xdf,
	0xac, 0xf5, 0x56, 0xf2, 0xa8, 0x0e, 0x67, 0xf4, 0x52, 0x44, 0xb5, 0xc5, 0xd0, 0xcb, 0x44, 0x01,
	0xcc, 0x3e, 0x08, 0x3b, 0x67, 0xe5, 0xf3, 0xe7, 0xec, 0x7a, 0xd6, 0xfb, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x74, 0x65, 0xc3, 0x11, 0x39, 0x01, 0x00, 0x00,
}
